/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSprintSimulatorRouteImport } from './routes/_authenticated/sprint-simulator'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInterventionsRouteImport } from './routes/_authenticated/interventions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as ApiPublicIngestSlackRouteImport } from './routes/api/public/ingest.slack'
import { Route as ApiPublicIngestJiraRouteImport } from './routes/api/public/ingest.jira'
import { Route as ApiPublicIngestGithubRouteImport } from './routes/api/public/ingest.github'
import { Route as ApiPublicIngestCalendarRouteImport } from './routes/api/public/ingest.calendar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSprintSimulatorRoute =
  AuthenticatedSprintSimulatorRouteImport.update({
    id: '/sprint-simulator',
    path: '/sprint-simulator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterventionsRoute =
  AuthenticatedInterventionsRouteImport.update({
    id: '/interventions',
    path: '/interventions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicIngestSlackRoute = ApiPublicIngestSlackRouteImport.update({
  id: '/api/public/ingest/slack',
  path: '/api/public/ingest/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestJiraRoute = ApiPublicIngestJiraRouteImport.update({
  id: '/api/public/ingest/jira',
  path: '/api/public/ingest/jira',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestGithubRoute = ApiPublicIngestGithubRouteImport.update({
  id: '/api/public/ingest/github',
  path: '/api/public/ingest/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestCalendarRoute = ApiPublicIngestCalendarRouteImport.update({
  id: '/api/public/ingest/calendar',
  path: '/api/public/ingest/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sprint-simulator': typeof AuthenticatedSprintSimulatorRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/public/ingest/calendar': typeof ApiPublicIngestCalendarRoute
  '/api/public/ingest/github': typeof ApiPublicIngestGithubRoute
  '/api/public/ingest/jira': typeof ApiPublicIngestJiraRoute
  '/api/public/ingest/slack': typeof ApiPublicIngestSlackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sprint-simulator': typeof AuthenticatedSprintSimulatorRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/public/ingest/calendar': typeof ApiPublicIngestCalendarRoute
  '/api/public/ingest/github': typeof ApiPublicIngestGithubRoute
  '/api/public/ingest/jira': typeof ApiPublicIngestJiraRoute
  '/api/public/ingest/slack': typeof ApiPublicIngestSlackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interventions': typeof AuthenticatedInterventionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sprint-simulator': typeof AuthenticatedSprintSimulatorRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/api/public/ingest/calendar': typeof ApiPublicIngestCalendarRoute
  '/api/public/ingest/github': typeof ApiPublicIngestGithubRoute
  '/api/public/ingest/jira': typeof ApiPublicIngestJiraRoute
  '/api/public/ingest/slack': typeof ApiPublicIngestSlackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/dashboard'
    | '/interventions'
    | '/settings'
    | '/sprint-simulator'
    | '/team'
    | '/api/public/ingest/calendar'
    | '/api/public/ingest/github'
    | '/api/public/ingest/jira'
    | '/api/public/ingest/slack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/dashboard'
    | '/interventions'
    | '/settings'
    | '/sprint-simulator'
    | '/team'
    | '/api/public/ingest/calendar'
    | '/api/public/ingest/github'
    | '/api/public/ingest/jira'
    | '/api/public/ingest/slack'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/interventions'
    | '/_authenticated/settings'
    | '/_authenticated/sprint-simulator'
    | '/_authenticated/team'
    | '/api/public/ingest/calendar'
    | '/api/public/ingest/github'
    | '/api/public/ingest/jira'
    | '/api/public/ingest/slack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicIngestCalendarRoute: typeof ApiPublicIngestCalendarRoute
  ApiPublicIngestGithubRoute: typeof ApiPublicIngestGithubRoute
  ApiPublicIngestJiraRoute: typeof ApiPublicIngestJiraRoute
  ApiPublicIngestSlackRoute: typeof ApiPublicIngestSlackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sprint-simulator': {
      id: '/_authenticated/sprint-simulator'
      path: '/sprint-simulator'
      fullPath: '/sprint-simulator'
      preLoaderRoute: typeof AuthenticatedSprintSimulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interventions': {
      id: '/_authenticated/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof AuthenticatedInterventionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/ingest/slack': {
      id: '/api/public/ingest/slack'
      path: '/api/public/ingest/slack'
      fullPath: '/api/public/ingest/slack'
      preLoaderRoute: typeof ApiPublicIngestSlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/jira': {
      id: '/api/public/ingest/jira'
      path: '/api/public/ingest/jira'
      fullPath: '/api/public/ingest/jira'
      preLoaderRoute: typeof ApiPublicIngestJiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/github': {
      id: '/api/public/ingest/github'
      path: '/api/public/ingest/github'
      fullPath: '/api/public/ingest/github'
      preLoaderRoute: typeof ApiPublicIngestGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/calendar': {
      id: '/api/public/ingest/calendar'
      path: '/api/public/ingest/calendar'
      fullPath: '/api/public/ingest/calendar'
      preLoaderRoute: typeof ApiPublicIngestCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterventionsRoute: typeof AuthenticatedInterventionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSprintSimulatorRoute: typeof AuthenticatedSprintSimulatorRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterventionsRoute: AuthenticatedInterventionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSprintSimulatorRoute: AuthenticatedSprintSimulatorRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicIngestCalendarRoute: ApiPublicIngestCalendarRoute,
  ApiPublicIngestGithubRoute: ApiPublicIngestGithubRoute,
  ApiPublicIngestJiraRoute: ApiPublicIngestJiraRoute,
  ApiPublicIngestSlackRoute: ApiPublicIngestSlackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
